# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAC Panamá - Voces en Off
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Mujeres en la colleción permanente del MAC.
baseurl: "" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://github.com/macpanama" # the base hostname & protocol for your site
logo: "/assets/img/logo/logo_macpanama_vocesenoff.png"
twitter_username: Panama_MAC
github_username:  macpanama
menu_heading: "Seleccione otra voz. <em>Choose another voice.</em>"
index_page_text: "Seleccione una voz. <em>Choose a voice.</em>"
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
